/**
 * Regenerates `supabase/setup.sql`, the one-paste route for the SQL Editor:
 * every migration in filename order, then the seed, then a PostgREST
 * schema-cache reload.
 *
 *   npm run db:build-setup
 *
 * Run it after adding or changing a migration or the seed. setup.sql is never
 * edited by hand, so this keeps it from drifting away from the migrations the
 * runner applies.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const SUPABASE_DIR = path.resolve(__dirname, '../../../supabase');
const MIGRATIONS_DIR = path.join(SUPABASE_DIR, 'migrations');
const OUTPUT_FILE = path.join(SUPABASE_DIR, 'setup.sql');

const RULE = `-- ${'='.repeat(77)}`;
const BANNER = `-- ${'#'.repeat(75)}`;

const sources = [
  ...readdirSync(MIGRATIONS_DIR)
    .filter((file) => file.endsWith('.sql'))
    .sort()
    .map((file) => `migrations/${file}`),
  'seed.sql',
];

const read = (relativePath: string): string =>
  readFileSync(path.join(SUPABASE_DIR, relativePath), 'utf8').replace(/\r\n/g, '\n').trimEnd();

const section = (title: string, body: string): string =>
  [BANNER, `-- ### ${title}`, BANNER, '', body].join('\n');

const header = [
  RULE,
  '-- setup.sql · complete database setup, generated from migrations/ + seed.sql',
  '--',
  '-- Paste this whole file into the Supabase SQL Editor and run it once.',
  '-- It applies every migration in order and loads the demo catalogue.',
  '--',
  '-- Safe to re-run: every statement is guarded with IF NOT EXISTS, ON CONFLICT,',
  '-- CREATE OR REPLACE or a freshness check.',
  '--',
  '-- Do NOT edit this file — edit the files under migrations/ and regenerate',
  '-- with `npm run db:build-setup` in backend/.',
  '-- Source files, in order:',
  ...sources.map((source) => `--   ${source}`),
  RULE,
].join('\n');

const output = [
  `${header}\n`,
  ...sources.map((source) => section(source, read(source))),
  section('Reload the PostgREST schema cache', "notify pgrst, 'reload schema';"),
].join('\n\n\n');

writeFileSync(OUTPUT_FILE, `${output}\n`, 'utf8');

console.log(`Wrote ${path.relative(process.cwd(), OUTPUT_FILE)} from ${sources.length} source files.`);
