-- =============================================================================
-- setup.sql · complete database setup, generated from migrations/ + seed.sql
--
-- Paste this whole file into the Supabase SQL Editor and run it once.
-- It applies every migration in order and loads the demo catalogue.
--
-- Safe to re-run: every statement is guarded with IF NOT EXISTS, ON CONFLICT,
-- CREATE OR REPLACE or a freshness check.
--
-- Do NOT edit this file — edit the files under migrations/ and regenerate
-- with `npm run db:build-setup` in backend/.
-- Source files, in order:
--   migrations/0001_extensions_and_enums.sql
--   migrations/0002_core_tables.sql
--   migrations/0003_carts_and_orders.sql
--   migrations/0004_functions.sql
--   migrations/0005_views.sql
--   migrations/0006_rls.sql
--   migrations/0007_storage.sql
--   migrations/0008_security_hardening.sql
--   migrations/0009_barcode_and_inventory_hardening.sql
--   seed.sql
-- =============================================================================



-- ###########################################################################
-- ### migrations/0001_extensions_and_enums.sql
-- ###########################################################################

-- =============================================================================
-- 0001 · Extensions and enumerated types
-- =============================================================================

create extension if not exists "pgcrypto";      -- gen_random_uuid()
create extension if not exists "pg_trgm";       -- trigram indexes for fuzzy product search
create extension if not exists "citext";        -- case-insensitive email

-- Roles a store user can hold. `admin` may mutate catalogue/inventory settings and
-- see financial summaries; `staff` runs the till (scan, cart, checkout).
do $$ begin
  create type user_role as enum ('admin', 'staff');
exception when duplicate_object then null; end $$;

-- Every stock delta is classified so the movement ledger stays auditable.
do $$ begin
  create type movement_type as enum (
    'purchase',    -- restock from a supplier
    'sale',        -- deducted by a completed order
    'adjustment',  -- manual correction by a user
    'return',      -- customer returned goods, stock comes back
    'damage'       -- write-off: expired / broken / shrinkage
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type cart_status as enum ('active', 'converted', 'abandoned');
exception when duplicate_object then null; end $$;

do $$ begin
  create type order_status as enum ('pending', 'completed', 'cancelled', 'refunded');
exception when duplicate_object then null; end $$;

do $$ begin
  create type payment_method as enum ('cash', 'card', 'upi', 'other');
exception when duplicate_object then null; end $$;

do $$ begin
  create type payment_status as enum ('pending', 'paid', 'failed', 'refunded');
exception when duplicate_object then null; end $$;

-- -----------------------------------------------------------------------------
-- Shared trigger: keep `updated_at` honest without trusting the client.
-- -----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;


-- ###########################################################################
-- ### migrations/0002_core_tables.sql
-- ###########################################################################

-- =============================================================================
-- 0002 · Users, categories, products, inventory, inventory ledger
-- =============================================================================

-- -----------------------------------------------------------------------------
-- users · application profile mirroring auth.users
-- Supabase Auth owns credentials; this table owns everything the store cares
-- about (role, display name, active flag).
-- -----------------------------------------------------------------------------
create table if not exists public.users (
  id          uuid primary key references auth.users (id) on delete cascade,
  email       citext      not null unique,
  full_name   text        not null default '',
  role        user_role   not null default 'staff',
  phone       text,
  avatar_url  text,
  is_active   boolean     not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists users_role_idx on public.users (role) where is_active;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at before update on public.users
  for each row execute function public.set_updated_at();

-- Provision a profile row automatically whenever Supabase Auth creates a user.
-- Role/name come from the sign-up metadata so the backend can create a staff
-- account in a single admin API call.
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
begin
  insert into public.users (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce((new.raw_user_meta_data ->> 'role')::user_role, 'staff')
  )
  on conflict (id) do nothing;
  return new;
end;
$fn$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_auth_user();

-- -----------------------------------------------------------------------------
-- categories
-- -----------------------------------------------------------------------------
create table if not exists public.categories (
  id          uuid primary key default gen_random_uuid(),
  name        text        not null,
  description text,
  color       text        not null default '#10B981',  -- accent used by the mobile UI
  icon        text        not null default 'basket-outline',
  is_active   boolean     not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Case-insensitive uniqueness: "Dairy" and "dairy" are the same aisle.
create unique index if not exists categories_name_unique_idx on public.categories (lower(name));
create index if not exists categories_active_idx on public.categories (is_active);

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at before update on public.categories
  for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- products
-- -----------------------------------------------------------------------------
create table if not exists public.products (
  id                  uuid primary key default gen_random_uuid(),
  name                text        not null,
  description         text,
  barcode             text        not null,
  sku                 text        not null,
  category_id         uuid        references public.categories (id) on delete set null,
  purchase_price      numeric(12, 2) not null default 0 check (purchase_price >= 0),
  selling_price       numeric(12, 2) not null check (selling_price >= 0),
  tax_rate            numeric(5, 2)  not null default 0 check (tax_rate >= 0 and tax_rate <= 100),
  unit                text        not null default 'pcs',
  image_url           text,
  low_stock_threshold integer     not null default 10 check (low_stock_threshold >= 0),
  is_active           boolean     not null default true,
  created_by          uuid        references public.users (id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- A barcode identifies exactly one product, and an SKU exactly one product.
-- Enforced across every row (not only active ones) so deactivating a product
-- never quietly frees its barcode for reuse — reactivate the original instead.
create unique index if not exists products_barcode_unique_idx on public.products (barcode);
create unique index if not exists products_sku_unique_idx     on public.products (upper(sku));

create index if not exists products_category_idx on public.products (category_id);
create index if not exists products_active_idx   on public.products (is_active);
create index if not exists products_created_idx  on public.products (created_at desc);
-- Trigram indexes keep substring search off a sequential scan as the catalogue grows.
create index if not exists products_name_trgm_idx on public.products using gin (name gin_trgm_ops);
create index if not exists products_sku_trgm_idx  on public.products using gin (sku gin_trgm_ops);

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products
  for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- inventory · exactly one stock row per product
-- Split out from `products` so stock writes never contend with catalogue edits
-- and so a single row can be locked during checkout.
-- -----------------------------------------------------------------------------
create table if not exists public.inventory (
  id              uuid primary key default gen_random_uuid(),
  product_id      uuid        not null unique references public.products (id) on delete cascade,
  quantity        integer     not null default 0 check (quantity >= 0),
  -- Reserved for a future "held for a pending order" flow; always 0 today.
  reserved        integer     not null default 0 check (reserved >= 0),
  last_counted_at timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists inventory_quantity_idx on public.inventory (quantity);

drop trigger if exists inventory_set_updated_at on public.inventory;
create trigger inventory_set_updated_at before update on public.inventory
  for each row execute function public.set_updated_at();

-- Every product gets a stock row the moment it is created.
create or replace function public.handle_new_product()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
begin
  insert into public.inventory (product_id, quantity)
  values (new.id, 0)
  on conflict (product_id) do nothing;
  return new;
end;
$fn$;

drop trigger if exists on_product_created on public.products;
create trigger on_product_created after insert on public.products
  for each row execute function public.handle_new_product();

-- -----------------------------------------------------------------------------
-- inventory_movements · append-only ledger
-- Rows are never updated or deleted; the running total in `inventory` is always
-- reproducible by replaying this table.
-- -----------------------------------------------------------------------------
create table if not exists public.inventory_movements (
  id                uuid primary key default gen_random_uuid(),
  product_id        uuid          not null references public.products (id) on delete cascade,
  type              movement_type not null,
  quantity_change   integer       not null check (quantity_change <> 0),
  previous_quantity integer       not null check (previous_quantity >= 0),
  new_quantity      integer       not null check (new_quantity >= 0),
  reason            text,
  reference_type    text,          -- e.g. 'order'
  reference_id      uuid,          -- e.g. orders.id
  created_by        uuid references public.users (id) on delete set null,
  created_at        timestamptz   not null default now()
);

create index if not exists movements_product_idx   on public.inventory_movements (product_id, created_at desc);
create index if not exists movements_created_idx   on public.inventory_movements (created_at desc);
create index if not exists movements_type_idx      on public.inventory_movements (type);
create index if not exists movements_reference_idx on public.inventory_movements (reference_type, reference_id);


-- ###########################################################################
-- ### migrations/0003_carts_and_orders.sql
-- ###########################################################################

-- =============================================================================
-- 0003 · Carts, orders, payments
-- =============================================================================

-- -----------------------------------------------------------------------------
-- carts · one open cart per user at a time
-- -----------------------------------------------------------------------------
create table if not exists public.carts (
  id         uuid        primary key default gen_random_uuid(),
  user_id    uuid        not null references public.users (id) on delete cascade,
  status     cart_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- The partial unique index is what makes "get or create the active cart" safe
-- under concurrency: two parallel requests cannot both create one.
create unique index if not exists carts_one_active_per_user_idx
  on public.carts (user_id) where status = 'active';
create index if not exists carts_user_idx on public.carts (user_id, created_at desc);

drop trigger if exists carts_set_updated_at on public.carts;
create trigger carts_set_updated_at before update on public.carts
  for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- cart_items
-- unit_price is snapshotted on add so a mid-transaction price edit cannot change
-- what the customer was quoted at the counter.
-- -----------------------------------------------------------------------------
create table if not exists public.cart_items (
  id         uuid        primary key default gen_random_uuid(),
  cart_id    uuid        not null references public.carts (id) on delete cascade,
  product_id uuid        not null references public.products (id) on delete cascade,
  quantity   integer     not null check (quantity > 0),
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  tax_rate   numeric(5, 2)  not null default 0 check (tax_rate >= 0 and tax_rate <= 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cart_items_unique_product unique (cart_id, product_id)
);

create index if not exists cart_items_cart_idx on public.cart_items (cart_id);

drop trigger if exists cart_items_set_updated_at on public.cart_items;
create trigger cart_items_set_updated_at before update on public.cart_items
  for each row execute function public.set_updated_at();

-- Touch the parent cart whenever its contents change, so "most recent cart"
-- ordering and stale-cart cleanup both work off carts.updated_at alone.
create or replace function public.touch_parent_cart()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
begin
  update public.carts set updated_at = now()
  where id = coalesce(new.cart_id, old.cart_id);
  return coalesce(new, old);
end;
$fn$;

drop trigger if exists cart_items_touch_cart on public.cart_items;
create trigger cart_items_touch_cart after insert or update or delete on public.cart_items
  for each row execute function public.touch_parent_cart();

-- -----------------------------------------------------------------------------
-- orders
-- -----------------------------------------------------------------------------
create sequence if not exists public.order_number_seq start 1000;

create table if not exists public.orders (
  id              uuid           primary key default gen_random_uuid(),
  order_number    text           not null unique,
  user_id         uuid           references public.users (id) on delete set null,
  cart_id         uuid           references public.carts (id) on delete set null,
  subtotal        numeric(12, 2) not null default 0 check (subtotal >= 0),
  tax_amount      numeric(12, 2) not null default 0 check (tax_amount >= 0),
  discount_amount numeric(12, 2) not null default 0 check (discount_amount >= 0),
  total_amount    numeric(12, 2) not null default 0 check (total_amount >= 0),
  item_count      integer        not null default 0 check (item_count >= 0),
  status          order_status   not null default 'completed',
  payment_method  payment_method not null default 'cash',
  payment_status  payment_status not null default 'paid',
  customer_name   text,
  customer_phone  text,
  notes           text,
  completed_at    timestamptz,
  created_at      timestamptz    not null default now(),
  updated_at      timestamptz    not null default now()
);

create index if not exists orders_user_idx    on public.orders (user_id, created_at desc);
create index if not exists orders_created_idx on public.orders (created_at desc);
create index if not exists orders_status_idx  on public.orders (status);
create index if not exists orders_number_idx  on public.orders (order_number);

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders
  for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- order_items
-- Product name/barcode/price are denormalised on purpose: a historical receipt
-- must keep reading correctly even after the product is renamed, repriced, or
-- removed from the catalogue.
-- -----------------------------------------------------------------------------
create table if not exists public.order_items (
  id           uuid           primary key default gen_random_uuid(),
  order_id     uuid           not null references public.orders (id) on delete cascade,
  product_id   uuid           references public.products (id) on delete set null,
  product_name text           not null,
  barcode      text,
  sku          text,
  quantity     integer        not null check (quantity > 0),
  unit_price   numeric(12, 2) not null check (unit_price >= 0),
  tax_rate     numeric(5, 2)  not null default 0,
  tax_amount   numeric(12, 2) not null default 0,
  line_total   numeric(12, 2) not null check (line_total >= 0),
  created_at   timestamptz    not null default now()
);

create index if not exists order_items_order_idx   on public.order_items (order_id);
create index if not exists order_items_product_idx on public.order_items (product_id);

-- -----------------------------------------------------------------------------
-- payments · one row per tender against an order
-- Modelled one-to-many so split payments can be added later without migration.
-- -----------------------------------------------------------------------------
create table if not exists public.payments (
  id         uuid           primary key default gen_random_uuid(),
  order_id   uuid           not null references public.orders (id) on delete cascade,
  method     payment_method not null,
  amount     numeric(12, 2) not null check (amount >= 0),
  status     payment_status not null default 'paid',
  reference  text,
  paid_at    timestamptz,
  created_at timestamptz    not null default now(),
  updated_at timestamptz    not null default now()
);

create index if not exists payments_order_idx on public.payments (order_id);

drop trigger if exists payments_set_updated_at on public.payments;
create trigger payments_set_updated_at before update on public.payments
  for each row execute function public.set_updated_at();


-- ###########################################################################
-- ### migrations/0004_functions.sql
-- ###########################################################################

-- =============================================================================
-- 0004 · Business logic that must be atomic lives in the database
--
-- Checkout and stock adjustment both read-then-write inventory. Doing that from
-- the API layer would race: two tills scanning the last unit could each read
-- quantity = 1 and both sell it. These functions run inside a single
-- transaction and take row locks, so the read and the write cannot be split.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Custom SQLSTATEs. Classes starting I–Z are reserved for user-defined codes,
-- and PostgREST surfaces them to the API as `error.code`, which lets the backend
-- map a domain failure onto the right HTTP status instead of a blanket 500.
--   ZS001 · insufficient stock          -> 409
--   ZS002 · cart is empty               -> 400
--   ZS003 · cart not found / not active -> 404
--   ZS004 · product inactive or missing -> 400
-- -----------------------------------------------------------------------------

-- -----------------------------------------------------------------------------
-- adjust_inventory · single source of truth for every stock delta
-- Locks the stock row, applies the change, and writes the ledger entry in one
-- shot so `inventory.quantity` and `inventory_movements` can never disagree.
-- -----------------------------------------------------------------------------
create or replace function public.adjust_inventory(
  p_product_id      uuid,
  p_quantity_change integer,
  p_type            movement_type,
  p_reason          text default null,
  p_user_id         uuid default null,
  p_reference_type  text default null,
  p_reference_id    uuid default null
)
returns public.inventory_movements
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_previous integer;
  v_new      integer;
  v_movement public.inventory_movements;
  v_name     text;
begin
  if p_quantity_change = 0 then
    raise exception 'Stock change must not be zero' using errcode = 'ZS004';
  end if;

  select p.name into v_name
  from public.products p
  where p.id = p_product_id and p.is_active;

  if v_name is null then
    raise exception 'Product not found or inactive' using errcode = 'ZS004';
  end if;

  -- FOR UPDATE serialises concurrent adjustments to the same product.
  select i.quantity into v_previous
  from public.inventory i
  where i.product_id = p_product_id
  for update;

  if v_previous is null then
    insert into public.inventory (product_id, quantity) values (p_product_id, 0)
    on conflict (product_id) do nothing;
    v_previous := 0;
  end if;

  v_new := v_previous + p_quantity_change;

  if v_new < 0 then
    raise exception 'Insufficient stock for %: have %, tried to remove %',
      v_name, v_previous, abs(p_quantity_change)
      using errcode = 'ZS001',
            detail  = json_build_object(
              'productId', p_product_id,
              'productName', v_name,
              'available', v_previous,
              'requested', abs(p_quantity_change)
            )::text;
  end if;

  update public.inventory
  set quantity = v_new,
      last_counted_at = case when p_type = 'adjustment' then now() else last_counted_at end
  where product_id = p_product_id;

  insert into public.inventory_movements (
    product_id, type, quantity_change, previous_quantity, new_quantity,
    reason, reference_type, reference_id, created_by
  )
  values (
    p_product_id, p_type, p_quantity_change, v_previous, v_new,
    p_reason, p_reference_type, p_reference_id, p_user_id
  )
  returning * into v_movement;

  return v_movement;
end;
$fn$;

-- -----------------------------------------------------------------------------
-- get_or_create_active_cart · idempotent, concurrency-safe
-- The partial unique index on carts(user_id) where status='active' turns a lost
-- race into a conflict we can recover from rather than a duplicate cart.
-- -----------------------------------------------------------------------------
create or replace function public.get_or_create_active_cart(p_user_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_cart_id uuid;
begin
  select id into v_cart_id
  from public.carts
  where user_id = p_user_id and status = 'active'
  limit 1;

  if v_cart_id is not null then
    return v_cart_id;
  end if;

  insert into public.carts (user_id, status)
  values (p_user_id, 'active')
  on conflict (user_id) where status = 'active' do nothing
  returning id into v_cart_id;

  if v_cart_id is null then
    -- Another transaction won the race; adopt its cart.
    select id into v_cart_id
    from public.carts
    where user_id = p_user_id and status = 'active'
    limit 1;
  end if;

  return v_cart_id;
end;
$fn$;

-- -----------------------------------------------------------------------------
-- checkout_cart · the atomic order pipeline
--
-- Validate stock -> create order -> create order items -> deduct inventory ->
-- record movements -> record payment -> close the cart. Every step shares one
-- transaction: any failure (including a concurrent sale emptying the shelf)
-- rolls the whole thing back, so an order never exists without its stock
-- deduction and stock is never deducted without an order.
-- -----------------------------------------------------------------------------
create or replace function public.checkout_cart(
  p_user_id         uuid,
  p_cart_id         uuid,
  p_payment_method  payment_method default 'cash',
  p_discount_amount numeric default 0,
  p_customer_name   text default null,
  p_customer_phone  text default null,
  p_notes           text default null,
  p_payment_reference text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_cart      public.carts;
  v_item      record;
  v_order_id  uuid;
  v_number    text;
  v_subtotal  numeric(12, 2) := 0;
  v_tax       numeric(12, 2) := 0;
  v_total     numeric(12, 2) := 0;
  v_count     integer := 0;
  v_discount  numeric(12, 2) := greatest(coalesce(p_discount_amount, 0), 0);
  v_line_net  numeric(12, 2);
  v_line_tax  numeric(12, 2);
begin
  select * into v_cart
  from public.carts
  where id = p_cart_id and user_id = p_user_id
  for update;

  if v_cart.id is null then
    raise exception 'Cart not found' using errcode = 'ZS003';
  end if;

  if v_cart.status <> 'active' then
    raise exception 'Cart has already been checked out' using errcode = 'ZS003';
  end if;

  if not exists (select 1 from public.cart_items where cart_id = p_cart_id) then
    raise exception 'Cart is empty' using errcode = 'ZS002';
  end if;

  -- Pass 1 · lock every stock row up front, ordered by product_id so two
  -- concurrent checkouts acquire locks in the same sequence and cannot deadlock.
  -- Totals are computed from the same locked snapshot that pass 2 writes to.
  for v_item in
    select ci.product_id,
           ci.quantity,
           ci.unit_price,
           ci.tax_rate,
           p.name  as product_name,
           p.barcode,
           p.sku,
           p.is_active,
           i.quantity as stock
    from public.cart_items ci
    join public.products  p on p.id = ci.product_id
    join public.inventory i on i.product_id = ci.product_id
    where ci.cart_id = p_cart_id
    order by ci.product_id
    for no key update of i
  loop
    if not v_item.is_active then
      raise exception 'Product % is no longer available', v_item.product_name
        using errcode = 'ZS004';
    end if;

    if v_item.stock < v_item.quantity then
      raise exception 'Insufficient stock for %: % available, % requested',
        v_item.product_name, v_item.stock, v_item.quantity
        using errcode = 'ZS001',
              detail  = json_build_object(
                'productId', v_item.product_id,
                'productName', v_item.product_name,
                'available', v_item.stock,
                'requested', v_item.quantity
              )::text;
    end if;

    v_line_net := round(v_item.unit_price * v_item.quantity, 2);
    v_line_tax := round(v_line_net * v_item.tax_rate / 100.0, 2);
    v_subtotal := v_subtotal + v_line_net;
    v_tax      := v_tax + v_line_tax;
    v_count    := v_count + v_item.quantity;
  end loop;

  -- A discount can never turn into a refund.
  v_discount := least(v_discount, v_subtotal + v_tax);
  v_total    := round(v_subtotal + v_tax - v_discount, 2);
  v_number   := 'ORD-' || to_char(now(), 'YYYYMMDD') || '-' ||
                lpad(nextval('public.order_number_seq')::text, 4, '0');

  insert into public.orders (
    order_number, user_id, cart_id, subtotal, tax_amount, discount_amount,
    total_amount, item_count, status, payment_method, payment_status,
    customer_name, customer_phone, notes, completed_at
  )
  values (
    v_number, p_user_id, p_cart_id, v_subtotal, v_tax, v_discount,
    v_total, v_count, 'completed', p_payment_method, 'paid',
    p_customer_name, p_customer_phone, p_notes, now()
  )
  returning id into v_order_id;

  -- Pass 2 · write the line items and burn the stock. The rows are still locked
  -- from pass 1, so the quantities validated above are the quantities deducted.
  for v_item in
    select ci.product_id, ci.quantity, ci.unit_price, ci.tax_rate,
           p.name as product_name, p.barcode, p.sku
    from public.cart_items ci
    join public.products p on p.id = ci.product_id
    where ci.cart_id = p_cart_id
    order by ci.product_id
  loop
    v_line_net := round(v_item.unit_price * v_item.quantity, 2);
    v_line_tax := round(v_line_net * v_item.tax_rate / 100.0, 2);

    insert into public.order_items (
      order_id, product_id, product_name, barcode, sku,
      quantity, unit_price, tax_rate, tax_amount, line_total
    )
    values (
      v_order_id, v_item.product_id, v_item.product_name, v_item.barcode, v_item.sku,
      v_item.quantity, v_item.unit_price, v_item.tax_rate, v_line_tax, v_line_net + v_line_tax
    );

    perform public.adjust_inventory(
      v_item.product_id,
      -v_item.quantity,
      'sale',
      'Order ' || v_number,
      p_user_id,
      'order',
      v_order_id
    );
  end loop;

  insert into public.payments (order_id, method, amount, status, reference, paid_at)
  values (v_order_id, p_payment_method, v_total, 'paid', p_payment_reference, now());

  -- Closing the cart is what "clears" it: the next get_or_create call opens a
  -- fresh one, while this cart stays queryable as part of the order trail.
  update public.carts set status = 'converted' where id = p_cart_id;
  delete from public.cart_items where cart_id = p_cart_id;

  return v_order_id;
end;
$fn$;

-- -----------------------------------------------------------------------------
-- dashboard_stats · one round trip instead of seven
-- -----------------------------------------------------------------------------
create or replace function public.dashboard_stats()
returns json
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_today_start timestamptz := date_trunc('day', now());
begin
  return json_build_object(
    'todaySales', (
      select coalesce(sum(total_amount), 0)::numeric(12, 2)
      from public.orders
      where status = 'completed' and created_at >= v_today_start
    ),
    'todayOrders', (
      select count(*) from public.orders
      where status = 'completed' and created_at >= v_today_start
    ),
    'totalOrders', (
      select count(*) from public.orders where status = 'completed'
    ),
    'totalSales', (
      select coalesce(sum(total_amount), 0)::numeric(12, 2)
      from public.orders where status = 'completed'
    ),
    'totalProducts', (
      select count(*) from public.products where is_active
    ),
    'totalCategories', (
      select count(*) from public.categories where is_active
    ),
    'lowStockCount', (
      select count(*)
      from public.products p
      join public.inventory i on i.product_id = p.id
      where p.is_active and i.quantity > 0 and i.quantity <= p.low_stock_threshold
    ),
    'outOfStockCount', (
      select count(*)
      from public.products p
      join public.inventory i on i.product_id = p.id
      where p.is_active and i.quantity = 0
    ),
    'inventoryUnits', (
      select coalesce(sum(i.quantity), 0)
      from public.inventory i
      join public.products p on p.id = i.product_id
      where p.is_active
    ),
    'inventoryRetailValue', (
      select coalesce(sum(i.quantity * p.selling_price), 0)::numeric(12, 2)
      from public.inventory i
      join public.products p on p.id = i.product_id
      where p.is_active
    ),
    'inventoryCostValue', (
      select coalesce(sum(i.quantity * p.purchase_price), 0)::numeric(12, 2)
      from public.inventory i
      join public.products p on p.id = i.product_id
      where p.is_active
    )
  );
end;
$fn$;

-- -----------------------------------------------------------------------------
-- sales_trend · totals per day for the dashboard chart
-- generate_series fills gaps so a day with no sales still plots as zero.
-- -----------------------------------------------------------------------------
create or replace function public.sales_trend(p_days integer default 7)
returns table (day date, total numeric, orders bigint)
language sql
security definer
set search_path = public
as $fn$
  select d::date as day,
         coalesce(sum(o.total_amount), 0)::numeric(12, 2) as total,
         count(o.id) as orders
  from generate_series(
         date_trunc('day', now()) - ((greatest(p_days, 1) - 1) * interval '1 day'),
         date_trunc('day', now()),
         interval '1 day'
       ) as d
  left join public.orders o
    on o.created_at >= d
   and o.created_at <  d + interval '1 day'
   and o.status = 'completed'
  group by d
  order by d;
$fn$;


-- ###########################################################################
-- ### migrations/0005_views.sql
-- ###########################################################################

-- =============================================================================
-- 0005 · Read models
--
-- `security_invoker = true` makes each view run under the querying role, so the
-- RLS policies in 0006 still apply. Without it a view would silently bypass
-- them, because a view otherwise executes as its owner.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- products_with_stock · the shape every product list in the app renders
-- Bundles the catalogue row, its category, live stock, and a derived status the
-- client can colour-code directly instead of recomputing the thresholds.
-- -----------------------------------------------------------------------------
create or replace view public.products_with_stock
with (security_invoker = true)
as
select
  p.id,
  p.name,
  p.description,
  p.barcode,
  p.sku,
  p.category_id,
  c.name  as category_name,
  c.color as category_color,
  c.icon  as category_icon,
  p.purchase_price,
  p.selling_price,
  p.tax_rate,
  p.unit,
  p.image_url,
  p.low_stock_threshold,
  p.is_active,
  p.created_by,
  p.created_at,
  p.updated_at,
  coalesce(i.quantity, 0) as quantity,
  coalesce(i.reserved, 0) as reserved,
  i.last_counted_at,
  case
    when coalesce(i.quantity, 0) = 0                        then 'out_of_stock'
    when coalesce(i.quantity, 0) <= p.low_stock_threshold   then 'low_stock'
    else 'in_stock'
  end as stock_status,
  round(coalesce(i.quantity, 0) * p.selling_price, 2) as stock_retail_value,
  round(p.selling_price - p.purchase_price, 2)        as margin
from public.products p
left join public.categories c on c.id = p.category_id
left join public.inventory  i on i.product_id = p.id;

-- -----------------------------------------------------------------------------
-- low_stock_products · restock worklist, most urgent first
-- -----------------------------------------------------------------------------
create or replace view public.low_stock_products
with (security_invoker = true)
as
select *
from public.products_with_stock
where is_active and stock_status in ('low_stock', 'out_of_stock')
order by quantity asc, name asc;

-- -----------------------------------------------------------------------------
-- inventory_movement_details · the audit trail, joined for display
-- -----------------------------------------------------------------------------
create or replace view public.inventory_movement_details
with (security_invoker = true)
as
select
  m.id,
  m.product_id,
  p.name    as product_name,
  p.barcode,
  p.sku,
  p.unit,
  p.image_url,
  m.type,
  m.quantity_change,
  m.previous_quantity,
  m.new_quantity,
  m.reason,
  m.reference_type,
  m.reference_id,
  m.created_by,
  u.full_name as created_by_name,
  m.created_at
from public.inventory_movements m
join public.products p on p.id = m.product_id
left join public.users u on u.id = m.created_by;

-- -----------------------------------------------------------------------------
-- order_summaries · order header plus who rang it up
-- -----------------------------------------------------------------------------
create or replace view public.order_summaries
with (security_invoker = true)
as
select
  o.*,
  u.full_name as cashier_name,
  u.email     as cashier_email
from public.orders o
left join public.users u on u.id = o.user_id;


-- ###########################################################################
-- ### migrations/0006_rls.sql
-- ###########################################################################

-- =============================================================================
-- 0006 · Row Level Security
--
-- The Node backend talks to Supabase with the service-role key, which bypasses
-- RLS entirely — authorisation for the REST API is enforced by its own
-- middleware. These policies are the second line of defence: they define what
-- an ordinary logged-in user could do if they ever held a user JWT and hit
-- PostgREST or Storage directly (which the mobile app does for image uploads).
--
-- Shape of the rules:
--   · catalogue (products, categories) — everyone reads, admins write
--   · stock (inventory, movements)     — everyone reads, nobody writes directly;
--                                        all mutations go through the SECURITY
--                                        DEFINER functions in 0004
--   · carts                            — strictly private to their owner
--   · orders                           — staff see their own, admins see all
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Helpers. SECURITY DEFINER is required: a policy on public.users that itself
-- queries public.users would recurse forever otherwise.
-- -----------------------------------------------------------------------------
create or replace function public.current_user_role()
returns user_role
language sql
stable
security definer
set search_path = public
as $fn$
  select role from public.users where id = auth.uid();
$fn$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $fn$
  select coalesce(public.current_user_role() = 'admin', false);
$fn$;

-- Any active member of staff. Deactivated accounts keep their auth session but
-- lose all data access.
create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $fn$
  select exists (
    select 1 from public.users
    where id = auth.uid() and is_active
  );
$fn$;

alter table public.users               enable row level security;
alter table public.categories          enable row level security;
alter table public.products            enable row level security;
alter table public.inventory           enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.carts               enable row level security;
alter table public.cart_items          enable row level security;
alter table public.orders              enable row level security;
alter table public.order_items         enable row level security;
alter table public.payments            enable row level security;

-- -----------------------------------------------------------------------------
-- users
-- -----------------------------------------------------------------------------
drop policy if exists users_select on public.users;
create policy users_select on public.users
  for select to authenticated
  using (id = auth.uid() or public.is_admin());

-- A user may edit their own profile. The role column is deliberately not
-- protected here at column level — the backend is the only writer that changes
-- roles, and it uses the service key.
drop policy if exists users_update_self on public.users;
create policy users_update_self on public.users
  for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

drop policy if exists users_admin_all on public.users;
create policy users_admin_all on public.users
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- -----------------------------------------------------------------------------
-- categories · read for staff, write for admins
-- -----------------------------------------------------------------------------
drop policy if exists categories_select on public.categories;
create policy categories_select on public.categories
  for select to authenticated using (public.is_staff());

drop policy if exists categories_admin_write on public.categories;
create policy categories_admin_write on public.categories
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- -----------------------------------------------------------------------------
-- products · read for staff, write for admins
-- -----------------------------------------------------------------------------
drop policy if exists products_select on public.products;
create policy products_select on public.products
  for select to authenticated using (public.is_staff());

drop policy if exists products_admin_write on public.products;
create policy products_admin_write on public.products
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- -----------------------------------------------------------------------------
-- inventory · readable, never directly writable
-- No INSERT/UPDATE/DELETE policy exists, so every write must come through
-- adjust_inventory()/checkout_cart(), which guarantees a matching ledger row.
-- -----------------------------------------------------------------------------
drop policy if exists inventory_select on public.inventory;
create policy inventory_select on public.inventory
  for select to authenticated using (public.is_staff());

drop policy if exists movements_select on public.inventory_movements;
create policy movements_select on public.inventory_movements
  for select to authenticated using (public.is_staff());

-- -----------------------------------------------------------------------------
-- carts · private to their owner
-- -----------------------------------------------------------------------------
drop policy if exists carts_own on public.carts;
create policy carts_own on public.carts
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists cart_items_own on public.cart_items;
create policy cart_items_own on public.cart_items
  for all to authenticated
  using (exists (
    select 1 from public.carts c
    where c.id = cart_items.cart_id and c.user_id = auth.uid()
  ))
  with check (exists (
    select 1 from public.carts c
    where c.id = cart_items.cart_id and c.user_id = auth.uid()
  ));

-- -----------------------------------------------------------------------------
-- orders · own orders for staff, everything for admins. Read-only from the
-- client: orders are only ever created by checkout_cart().
-- -----------------------------------------------------------------------------
drop policy if exists orders_select on public.orders;
create policy orders_select on public.orders
  for select to authenticated
  using (user_id = auth.uid() or public.is_admin());

drop policy if exists order_items_select on public.order_items;
create policy order_items_select on public.order_items
  for select to authenticated
  using (exists (
    select 1 from public.orders o
    where o.id = order_items.order_id
      and (o.user_id = auth.uid() or public.is_admin())
  ));

drop policy if exists payments_select on public.payments;
create policy payments_select on public.payments
  for select to authenticated
  using (exists (
    select 1 from public.orders o
    where o.id = payments.order_id
      and (o.user_id = auth.uid() or public.is_admin())
  ));

-- -----------------------------------------------------------------------------
-- Function execution grants
-- -----------------------------------------------------------------------------
grant execute on function public.get_or_create_active_cart(uuid) to authenticated;
grant execute on function public.dashboard_stats()               to authenticated;
grant execute on function public.sales_trend(integer)            to authenticated;

-- checkout_cart and adjust_inventory take a caller-supplied user id, so leaving
-- them executable by `authenticated` would let any user act as another. They
-- stay service-role only; the backend is the sole entry point.
revoke execute on function public.checkout_cart(uuid, uuid, payment_method, numeric, text, text, text, text) from authenticated, anon;
revoke execute on function public.adjust_inventory(uuid, integer, movement_type, text, uuid, text, uuid) from authenticated, anon;


-- ###########################################################################
-- ### migrations/0007_storage.sql
-- ###########################################################################

-- =============================================================================
-- 0007 · Storage bucket for product images
--
-- The bucket is public-read so <Image source={{ uri }}> works without signing
-- every URL on a screen full of products. Writes stay restricted to staff.
-- =============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images',
  'product-images',
  true,
  5242880,  -- 5 MB
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic']
)
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "product images are publicly readable" on storage.objects;
create policy "product images are publicly readable" on storage.objects
  for select to public
  using (bucket_id = 'product-images');

drop policy if exists "staff can upload product images" on storage.objects;
create policy "staff can upload product images" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'product-images' and public.is_staff());

drop policy if exists "staff can replace product images" on storage.objects;
create policy "staff can replace product images" on storage.objects
  for update to authenticated
  using (bucket_id = 'product-images' and public.is_staff())
  with check (bucket_id = 'product-images' and public.is_staff());

drop policy if exists "admins can delete product images" on storage.objects;
create policy "admins can delete product images" on storage.objects
  for delete to authenticated
  using (bucket_id = 'product-images' and public.is_admin());


-- ###########################################################################
-- ### migrations/0008_security_hardening.sql
-- ###########################################################################

-- =============================================================================
-- 0008 · Security hardening
--
-- Closes three holes in what a client can reach directly with the anon key the
-- mobile app ships (PostgREST at /rest/v1, Storage at /storage/v1):
--
--   1. Privilege escalation. `users_update_self` let a signed-in user update
--      every column of their own profile — `role` and `is_active` included — so
--      any member of staff could make themselves an admin.
--   2. Self-service admin sign-up. `handle_new_auth_user()` took the role from
--      sign-up metadata, which whoever is signing up controls.
--   3. Callable SECURITY DEFINER functions. Postgres grants EXECUTE on every new
--      function to PUBLIC, and 0006 only revoked it from `anon, authenticated`,
--      so `adjust_inventory` and `checkout_cart` stayed callable through /rpc by
--      anyone holding the anon key — no sign-in needed.
--
-- The model after this migration: the API, using the service-role key, is the
-- only writer of application data. Clients may read through RLS as a signed-in
-- user and upload product images to Storage; nothing else.
--
-- Any table or function added after this one must follow the same rules:
-- revoke client write privileges on new tables, and revoke EXECUTE from PUBLIC
-- (not only from anon/authenticated) on any function a client must not call.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1 · Clients never write application tables directly
--
-- Supabase grants ALL on public tables to anon and authenticated by default and
-- relies on RLS alone. Taking the write privileges away means a policy written
-- too loosely in future cannot reopen this hole on its own.
-- -----------------------------------------------------------------------------
revoke all on table
  public.users,
  public.categories,
  public.products,
  public.inventory,
  public.inventory_movements,
  public.carts,
  public.cart_items,
  public.orders,
  public.order_items,
  public.payments,
  public.products_with_stock,
  public.low_stock_products,
  public.inventory_movement_details,
  public.order_summaries
from anon, authenticated;

-- Signed-in reads stay possible, still filtered row by row by the policies in 0006.
grant select on table
  public.users,
  public.categories,
  public.products,
  public.inventory,
  public.inventory_movements,
  public.carts,
  public.cart_items,
  public.orders,
  public.order_items,
  public.payments,
  public.products_with_stock,
  public.low_stock_products,
  public.inventory_movement_details,
  public.order_summaries
to authenticated;

revoke all on sequence public.order_number_seq from anon, authenticated;

-- The self-update policy is the escalation route itself, and the admin
-- write-everything policy has no remaining use now that clients cannot write.
drop policy if exists users_update_self on public.users;
drop policy if exists users_admin_all   on public.users;

-- The migration runner's ledger lives in public too, so it is exposed through
-- PostgREST like any other table. It only exists when the runner was used.
do $$
begin
  if to_regclass('public.schema_migrations') is not null then
    execute 'alter table public.schema_migrations enable row level security';
    execute 'revoke all on table public.schema_migrations from anon, authenticated';
  end if;
end;
$$;

-- -----------------------------------------------------------------------------
-- 2 · Roles come only from the service role
--
-- `raw_app_meta_data` can only be written with the service-role key, unlike
-- `raw_user_meta_data`, which the person signing up chooses. The API marks the
-- accounts it creates with `store_account: true`; anything else — a sign-up
-- made directly against Supabase Auth with the anon key — lands as an inactive
-- member of staff that an admin has to approve before it can do anything.
-- -----------------------------------------------------------------------------
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_provisioned boolean := coalesce(new.raw_app_meta_data ->> 'store_account', '') = 'true';
  v_role        user_role := 'staff';
begin
  if v_provisioned and (new.raw_app_meta_data ->> 'role') in ('admin', 'staff') then
    v_role := (new.raw_app_meta_data ->> 'role')::user_role;
  end if;

  insert into public.users (id, email, full_name, role, is_active)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    v_role,
    v_provisioned
  )
  on conflict (id) do nothing;

  return new;
end;
$fn$;

-- A deactivated admin keeps a valid JWT until it expires; the role check in
-- RLS and Storage must not keep honouring it in the meantime.
create or replace function public.current_user_role()
returns user_role
language sql
stable
security definer
set search_path = public
as $fn$
  select role from public.users where id = auth.uid() and is_active;
$fn$;

-- -----------------------------------------------------------------------------
-- 3 · Function execution
--
-- Revoking from PUBLIC is the part 0006 missed: anon and authenticated inherit
-- PUBLIC's grant, so revoking from them by name changed nothing. All five
-- business functions are called only by the API, as service_role.
-- -----------------------------------------------------------------------------
revoke execute on function public.adjust_inventory(uuid, integer, movement_type, text, uuid, text, uuid)
  from public, anon, authenticated;
revoke execute on function public.checkout_cart(uuid, uuid, payment_method, numeric, text, text, text, text)
  from public, anon, authenticated;
revoke execute on function public.get_or_create_active_cart(uuid) from public, anon, authenticated;
revoke execute on function public.dashboard_stats()               from public, anon, authenticated;
revoke execute on function public.sales_trend(integer)            from public, anon, authenticated;

grant execute on function public.adjust_inventory(uuid, integer, movement_type, text, uuid, text, uuid)
  to service_role;
grant execute on function public.checkout_cart(uuid, uuid, payment_method, numeric, text, text, text, text)
  to service_role;
grant execute on function public.get_or_create_active_cart(uuid) to service_role;
grant execute on function public.dashboard_stats()               to service_role;
grant execute on function public.sales_trend(integer)            to service_role;

-- The RLS and Storage helpers only ever run inside policies for signed-in
-- users, so the anonymous role has no reason to call them.
revoke execute on function public.current_user_role() from public, anon;
revoke execute on function public.is_admin()          from public, anon;
revoke execute on function public.is_staff()          from public, anon;

grant execute on function public.current_user_role() to authenticated, service_role;
grant execute on function public.is_admin()          to authenticated, service_role;
grant execute on function public.is_staff()          to authenticated, service_role;


-- ###########################################################################
-- ### migrations/0009_barcode_and_inventory_hardening.sql
-- ###########################################################################

-- =============================================================================
-- 0009 · Barcode and inventory hardening
--
--   1. One barcode, one product, in any GTIN format. A phone camera reads a
--      UPC-A as 12 digits on Android but as the 13-digit EAN with a leading
--      zero on iOS, so the same packet must be found — and be unique — under
--      either form.
--   2. A movement's type fixes its direction: purchases and returns only add,
--      sales and damage only remove, adjustments go either way.
--   3. A retried stock change applies once. The app sends an idempotency key
--      with every manual change; a resend after a timeout replays the original
--      result instead of moving stock a second time.
--   4. Recounts are absolute. "8 on the shelf" becomes a delta under the row
--      lock, so sales made while the count screen was open cannot skew it.
--   5. Adding to the cart is a single upsert, so two quick scans of the same
--      item add two units instead of the second failing on the unique index.
--   6. The inventory summary is one aggregate instead of every product row
--      shipped to the API, which PostgREST caps at 1000 rows.
--
-- Per 0008: the new table refuses client writes, and the new functions are
-- revoked from PUBLIC and granted to service_role only.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1 · Barcode matching key
--
-- Numeric codes of a GTIN length (8, 12, 13, 14 digits) are padded to GTIN-14,
-- which is how GS1 defines them to compare. Anything else — Code 128 shelf
-- labels, internal codes — must match exactly. The backend's
-- src/utils/barcode.ts mirrors this function; the two must change together.
-- -----------------------------------------------------------------------------
create or replace function public.barcode_key(p_barcode text)
returns text
language sql
immutable
parallel safe
set search_path = pg_catalog
as $fn$
  select case
           when b ~ '^([0-9]{8}|[0-9]{12,14})$' then lpad(b, 14, '0')
           else b
         end
  from (select btrim(p_barcode) as b) as s;
$fn$;

-- Stop with the offending codes named, rather than on an anonymous unique-index
-- error, if the catalogue already holds one product under two formats.
do $$
declare
  v_duplicates text;
begin
  select string_agg(codes, '; ')
  into v_duplicates
  from (
    select string_agg(barcode, ' = ' order by barcode) as codes
    from public.products
    group by public.barcode_key(barcode)
    having count(*) > 1
  ) as clashes;

  if v_duplicates is not null then
    raise exception 'These products share one barcode written in different formats: %. '
                    'Recode or merge them, then re-run the migration.', v_duplicates;
  end if;
end;
$$;

alter table public.products
  add column if not exists barcode_key text generated always as (public.barcode_key(barcode)) stored;

create unique index if not exists products_barcode_key_unique_idx on public.products (barcode_key);

-- The API validates barcodes the same way; this keeps any other writer honest.
-- NOT VALID: enforced on new and changed rows without rechecking legacy data.
alter table public.products drop constraint if exists products_barcode_format_chk;
alter table public.products
  add constraint products_barcode_format_chk
  check (barcode = btrim(barcode) and barcode ~ '^[A-Za-z0-9._-]{4,64}$') not valid;

-- -----------------------------------------------------------------------------
-- 2 · Idempotency keys for manual stock changes
--
-- One row per request key, written in the same transaction as the change it
-- guards, so a key exists if and only if its change happened. It stores the
-- request too: replaying a key with a different product or quantity is refused
-- rather than silently answered with someone else's result.
-- -----------------------------------------------------------------------------
create table if not exists public.inventory_request_keys (
  key               uuid          primary key,
  operation         text          not null check (operation in ('adjust', 'count')),
  product_id        uuid          not null references public.products (id) on delete cascade,
  movement_type     movement_type not null,
  -- The signed change for 'adjust'; the counted total for 'count'.
  quantity          integer       not null,
  -- Null for a count that matched the shelf: nothing moved, but the key still
  -- has to answer a retry.
  movement_id       uuid          references public.inventory_movements (id) on delete set null,
  previous_quantity integer       not null,
  new_quantity      integer       not null,
  created_by        uuid          references public.users (id) on delete set null,
  created_at        timestamptz   not null default now()
);

-- Keys only need to outlive a client's retry window; this index makes pruning
-- old ones (e.g. older than 30 days) cheap.
create index if not exists inventory_request_keys_created_idx on public.inventory_request_keys (created_at);

alter table public.inventory_request_keys enable row level security;
revoke all on table public.inventory_request_keys from anon, authenticated;

-- -----------------------------------------------------------------------------
-- 3 · adjust_inventory, now direction-checked and idempotent
--
-- Dropped first: adding a parameter with a default creates an overload, and the
-- old seven-argument version would then make every existing call ambiguous.
-- checkout_cart calls it positionally with seven arguments, which resolves to
-- this version through the default.
-- -----------------------------------------------------------------------------
drop function if exists public.adjust_inventory(uuid, integer, movement_type, text, uuid, text, uuid);

create or replace function public.adjust_inventory(
  p_product_id      uuid,
  p_quantity_change integer,
  p_type            movement_type,
  p_reason          text default null,
  p_user_id         uuid default null,
  p_reference_type  text default null,
  p_reference_id    uuid default null,
  p_idempotency_key uuid default null
)
returns public.inventory_movements
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_previous integer;
  v_new      integer;
  v_movement public.inventory_movements;
  v_name     text;
  v_key      public.inventory_request_keys;
begin
  if p_quantity_change is null or p_quantity_change = 0 then
    raise exception 'Stock change must not be zero' using errcode = 'ZS006';
  end if;

  if p_type in ('purchase', 'return') and p_quantity_change < 0 then
    raise exception 'A % can only add stock', p_type using errcode = 'ZS006';
  end if;

  if p_type in ('sale', 'damage') and p_quantity_change > 0 then
    raise exception 'A % can only remove stock', p_type using errcode = 'ZS006';
  end if;

  select p.name into v_name
  from public.products p
  where p.id = p_product_id and p.is_active;

  if v_name is null then
    raise exception 'Product not found or inactive' using errcode = 'ZS004';
  end if;

  -- Make sure the stock row exists, then lock it. The lock serialises every
  -- change to this product — including two deliveries of the same request key,
  -- so the second one reliably sees the first's key below.
  insert into public.inventory (product_id, quantity) values (p_product_id, 0)
  on conflict (product_id) do nothing;

  select i.quantity into v_previous
  from public.inventory i
  where i.product_id = p_product_id
  for update;

  if p_idempotency_key is not null then
    select * into v_key from public.inventory_request_keys where key = p_idempotency_key;

    if found then
      if v_key.operation <> 'adjust'
         or v_key.product_id <> p_product_id
         or v_key.movement_type <> p_type
         or v_key.quantity <> p_quantity_change then
        raise exception 'This request key was already used for a different stock change'
          using errcode = 'ZS005';
      end if;

      select * into v_movement from public.inventory_movements where id = v_key.movement_id;
      return v_movement;
    end if;
  end if;

  v_new := v_previous + p_quantity_change;

  if v_new < 0 then
    raise exception 'Insufficient stock for %: have %, tried to remove %',
      v_name, v_previous, abs(p_quantity_change)
      using errcode = 'ZS001',
            detail  = json_build_object(
              'productId', p_product_id,
              'productName', v_name,
              'available', v_previous,
              'requested', abs(p_quantity_change)
            )::text;
  end if;

  update public.inventory
  set quantity = v_new,
      last_counted_at = case when p_type = 'adjustment' then now() else last_counted_at end
  where product_id = p_product_id;

  insert into public.inventory_movements (
    product_id, type, quantity_change, previous_quantity, new_quantity,
    reason, reference_type, reference_id, created_by
  )
  values (
    p_product_id, p_type, p_quantity_change, v_previous, v_new,
    p_reason, p_reference_type, p_reference_id, p_user_id
  )
  returning * into v_movement;

  if p_idempotency_key is not null then
    insert into public.inventory_request_keys (
      key, operation, product_id, movement_type, quantity,
      movement_id, previous_quantity, new_quantity, created_by
    )
    values (
      p_idempotency_key, 'adjust', p_product_id, p_type, p_quantity_change,
      v_movement.id, v_previous, v_new, p_user_id
    );
  end if;

  return v_movement;
end;
$fn$;

-- -----------------------------------------------------------------------------
-- 4 · set_inventory_count · "there are N on the shelf"
--
-- The delta is worked out here, from the quantity the count replaces, while the
-- row is locked. Worked out on the phone it would be based on whatever the
-- screen loaded, and every sale since then would be counted twice.
-- -----------------------------------------------------------------------------
create or replace function public.set_inventory_count(
  p_product_id       uuid,
  p_counted_quantity integer,
  p_reason           text default null,
  p_user_id          uuid default null,
  p_idempotency_key  uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_previous integer;
  v_movement public.inventory_movements;
  v_key      public.inventory_request_keys;
  v_name     text;
  v_changed  boolean;
begin
  if p_counted_quantity is null or p_counted_quantity < 0 then
    raise exception 'Counted quantity cannot be negative' using errcode = 'ZS006';
  end if;

  select p.name into v_name
  from public.products p
  where p.id = p_product_id and p.is_active;

  if v_name is null then
    raise exception 'Product not found or inactive' using errcode = 'ZS004';
  end if;

  insert into public.inventory (product_id, quantity) values (p_product_id, 0)
  on conflict (product_id) do nothing;

  select i.quantity into v_previous
  from public.inventory i
  where i.product_id = p_product_id
  for update;

  if p_idempotency_key is not null then
    select * into v_key from public.inventory_request_keys where key = p_idempotency_key;

    if found then
      if v_key.operation <> 'count'
         or v_key.product_id <> p_product_id
         or v_key.quantity <> p_counted_quantity then
        raise exception 'This request key was already used for a different stock change'
          using errcode = 'ZS005';
      end if;

      if v_key.movement_id is not null then
        select * into v_movement from public.inventory_movements where id = v_key.movement_id;
      end if;

      return jsonb_build_object(
        'changed', v_key.movement_id is not null,
        'previousQuantity', v_key.previous_quantity,
        'newQuantity', v_key.new_quantity,
        'movement', case when v_key.movement_id is null then null else to_jsonb(v_movement) end,
        'replayed', true
      );
    end if;
  end if;

  v_changed := p_counted_quantity <> v_previous;

  if v_changed then
    -- Same transaction and the lock is already held, so this cannot interleave.
    v_movement := public.adjust_inventory(
      p_product_id,
      p_counted_quantity - v_previous,
      'adjustment',
      p_reason,
      p_user_id,
      'count',
      null,
      null
    );
  else
    -- Nothing moved, but the shelf was counted, which is worth recording.
    update public.inventory set last_counted_at = now() where product_id = p_product_id;
  end if;

  if p_idempotency_key is not null then
    insert into public.inventory_request_keys (
      key, operation, product_id, movement_type, quantity,
      movement_id, previous_quantity, new_quantity, created_by
    )
    values (
      p_idempotency_key, 'count', p_product_id, 'adjustment', p_counted_quantity,
      case when v_changed then v_movement.id end, v_previous, p_counted_quantity, p_user_id
    );
  end if;

  return jsonb_build_object(
    'changed', v_changed,
    'previousQuantity', v_previous,
    'newQuantity', p_counted_quantity,
    'movement', case when v_changed then to_jsonb(v_movement) else null end,
    'replayed', false
  );
end;
$fn$;

-- -----------------------------------------------------------------------------
-- 5 · add_cart_item · one scan, one atomic upsert
--
-- Reading the line and then inserting or updating it from the API raced: two
-- quick scans of one item both saw no line, both inserted, and the second hit
-- cart_items_unique_product. The upsert adds to whatever is there at commit.
-- The stock check here is advisory — checkout re-checks under lock — but it
-- keeps the cashier from ringing up more than the shelf holds.
-- -----------------------------------------------------------------------------
create or replace function public.add_cart_item(
  p_user_id    uuid,
  p_product_id uuid,
  p_quantity   integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_product  public.products;
  v_cart_id  uuid;
  v_stock    integer;
  v_quantity integer;
  v_inserted boolean;
begin
  if p_quantity is null or p_quantity < 1 then
    raise exception 'Quantity must be at least 1' using errcode = 'ZS006';
  end if;

  select * into v_product from public.products where id = p_product_id;

  if v_product.id is null or not v_product.is_active then
    raise exception 'Product not found or inactive' using errcode = 'ZS004';
  end if;

  -- Checkout locks the cart row too, so a scan cannot land in a cart that is
  -- being turned into an order. If checkout won, the next attempt gets the
  -- fresh cart that replaces it.
  for attempt in 1..2 loop
    v_cart_id := public.get_or_create_active_cart(p_user_id);
    perform 1 from public.carts where id = v_cart_id and status = 'active' for update;
    exit when found;
    v_cart_id := null;
  end loop;

  if v_cart_id is null then
    raise exception 'Could not open a cart, please retry' using errcode = 'ZS003';
  end if;

  select coalesce(i.quantity, 0) into v_stock
  from public.inventory i
  where i.product_id = p_product_id;

  v_stock := coalesce(v_stock, 0);

  insert into public.cart_items as ci (cart_id, product_id, quantity, unit_price, tax_rate)
  values (v_cart_id, p_product_id, p_quantity, v_product.selling_price, v_product.tax_rate)
  on conflict (cart_id, product_id) do update
    set quantity   = ci.quantity + excluded.quantity,
        unit_price = excluded.unit_price,
        tax_rate   = excluded.tax_rate
  returning ci.quantity, (ci.xmax = 0) into v_quantity, v_inserted;

  if v_quantity > v_stock then
    raise exception '%',
      case
        when v_stock <= 0 then format('%s is out of stock', v_product.name)
        else format('Only %s %s of %s left in stock', v_stock, v_product.unit, v_product.name)
      end
      using errcode = 'ZS001',
            detail  = json_build_object(
              'productId', p_product_id,
              'productName', v_product.name,
              'available', greatest(v_stock, 0),
              'requested', v_quantity
            )::text;
  end if;

  return jsonb_build_object(
    'cartId', v_cart_id,
    'quantityInCart', v_quantity,
    'wasAlreadyInCart', not v_inserted
  );
end;
$fn$;

-- -----------------------------------------------------------------------------
-- 6 · inventory_summary · one consistent snapshot
-- The bands match products_with_stock.stock_status exactly.
-- -----------------------------------------------------------------------------
create or replace function public.inventory_summary()
returns jsonb
language sql
stable
security definer
set search_path = public
as $fn$
  select jsonb_build_object(
    'totalProducts', count(*),
    'inStock',       count(*) filter (where coalesce(i.quantity, 0) > p.low_stock_threshold),
    'lowStock',      count(*) filter (where coalesce(i.quantity, 0) > 0
                                        and coalesce(i.quantity, 0) <= p.low_stock_threshold),
    'outOfStock',    count(*) filter (where coalesce(i.quantity, 0) = 0),
    'totalUnits',    coalesce(sum(coalesce(i.quantity, 0)), 0),
    'retailValue',   round(coalesce(sum(coalesce(i.quantity, 0) * p.selling_price), 0), 2),
    'costValue',     round(coalesce(sum(coalesce(i.quantity, 0) * p.purchase_price), 0), 2)
  )
  from public.products p
  left join public.inventory i on i.product_id = p.id
  where p.is_active;
$fn$;

-- -----------------------------------------------------------------------------
-- 7 · Function execution (see 0008 §3)
-- barcode_key stays callable: it is a pure helper behind a generated column.
-- -----------------------------------------------------------------------------
revoke execute on function public.adjust_inventory(uuid, integer, movement_type, text, uuid, text, uuid, uuid)
  from public, anon, authenticated;
revoke execute on function public.set_inventory_count(uuid, integer, text, uuid, uuid)
  from public, anon, authenticated;
revoke execute on function public.add_cart_item(uuid, uuid, integer) from public, anon, authenticated;
revoke execute on function public.inventory_summary()                from public, anon, authenticated;

grant execute on function public.adjust_inventory(uuid, integer, movement_type, text, uuid, text, uuid, uuid)
  to service_role;
grant execute on function public.set_inventory_count(uuid, integer, text, uuid, uuid) to service_role;
grant execute on function public.add_cart_item(uuid, uuid, integer) to service_role;
grant execute on function public.inventory_summary()                to service_role;

-- PostgREST only learns about new functions and columns on a schema reload.
notify pgrst, 'reload schema';


-- ###########################################################################
-- ### seed.sql
-- ###########################################################################

-- =============================================================================
-- seed.sql · demo catalogue for local development and testing
--
-- Safe to run more than once: every statement is guarded by ON CONFLICT or a
-- freshness check, so re-running will not duplicate rows or double stock.
--
-- Barcodes are real, check-digit-valid EAN-13 numbers, so a physical scanner
-- (or a printed/on-screen barcode) reads them correctly during testing.
--
-- Staff accounts are NOT seeded here — Supabase Auth owns credentials. Create
-- them with:  npm run seed:users --prefix backend
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Categories
-- -----------------------------------------------------------------------------
insert into public.categories (name, description, color, icon) values
  ('Fruits & Vegetables', 'Fresh produce, sold by weight or piece', '#22C55E', 'nutrition-outline'),
  ('Dairy & Eggs',        'Milk, cheese, butter, yoghurt and eggs',  '#38BDF8', 'egg-outline'),
  ('Bakery',              'Bread, buns and everyday baked goods',    '#F59E0B', 'pizza-outline'),
  ('Beverages',           'Water, juices, soft and hot drinks',      '#06B6D4', 'wine-outline'),
  ('Snacks',              'Biscuits, chips, chocolate and namkeen',  '#F97316', 'fast-food-outline'),
  ('Staples & Grains',    'Rice, flour, pulses, sugar and oils',     '#8B5CF6', 'basket-outline'),
  ('Household',           'Cleaning, laundry and paper goods',       '#64748B', 'home-outline')
on conflict (lower(name)) do nothing;

-- -----------------------------------------------------------------------------
-- Products
-- Prices are in whole currency units (₹ by default — see CURRENCY in the env).
-- -----------------------------------------------------------------------------
insert into public.products
  (name, description, barcode, sku, category_id, purchase_price, selling_price, tax_rate, unit, low_stock_threshold)
select
  s.name, s.description, s.barcode, s.sku, c.id,
  s.purchase_price, s.selling_price, s.tax_rate, s.unit, s.threshold
from (values
  -- name                        description                                  barcode          sku          category               buy      sell     tax    unit    low
  ('Amul Toned Milk 1L',        'Homogenised toned milk, 1 litre pouch',      '8901030100000', 'DRY-MLK-1L', 'Dairy & Eggs',        52.00,   62.00,  0.00,  'pack',  12),
  ('Farm Eggs (Tray of 6)',     'Free-range brown eggs, tray of six',         '8901030107917', 'DRY-EGG-06', 'Dairy & Eggs',        48.00,   66.00,  0.00,  'tray',  10),
  ('Amul Butter 500g',          'Pasteurised salted table butter',            '8901030115837', 'DRY-BTR-500','Dairy & Eggs',       245.00,  285.00,  5.00,  'pack',   6),
  ('Greek Yoghurt 400g',        'Thick set curd, no added sugar',             '8901030123757', 'DRY-YOG-400','Dairy & Eggs',        62.00,   85.00,  5.00,  'cup',    8),
  ('Cheddar Cheese Slices',     'Processed cheddar, 10 slices',               '8901030131677', 'DRY-CHS-10', 'Dairy & Eggs',       105.00,  139.00, 12.00,  'pack',   6),

  ('Whole Wheat Bread 400g',    'Soft sandwich loaf, baked daily',            '8901058139594', 'BAK-BRD-400','Bakery',              38.00,   50.00,  5.00,  'loaf',  10),
  ('Butter Croissant',          'All-butter flaky croissant',                 '8901058147513', 'BAK-CRS-01', 'Bakery',              22.00,   45.00,  5.00,  'pcs',   12),
  ('Multigrain Buns (Pack 6)',  'Six seeded burger buns',                     '8901058155433', 'BAK-BUN-06', 'Bakery',              34.00,   55.00,  5.00,  'pack',   8),
  ('Chocolate Muffin',          'Double chocolate muffin, single serve',      '8901058163353', 'BAK-MUF-01', 'Bakery',              25.00,   49.00, 12.00,  'pcs',   10),
  ('Rusk Toast 300g',           'Crisp cardamom rusk',                        '8901058171273', 'BAK-RSK-300','Bakery',              32.00,   48.00,  5.00,  'pack',   8),

  ('Bananas (Robusta) 1kg',     'Ripe robusta bananas, per kilo',             '8901725179199', 'FRV-BAN-1K', 'Fruits & Vegetables', 32.00,   54.00,  0.00,  'kg',    15),
  ('Tomatoes 1kg',              'Fresh local tomatoes, per kilo',             '8901725187101', 'FRV-TOM-1K', 'Fruits & Vegetables', 24.00,   42.00,  0.00,  'kg',    20),
  ('Onions 1kg',                'Red onions, per kilo',                       '8901725195021', 'FRV-ONI-1K', 'Fruits & Vegetables', 22.00,   38.00,  0.00,  'kg',    20),
  ('Baby Spinach 250g',         'Washed and ready-to-cook spinach',           '8901725202941', 'FRV-SPN-250','Fruits & Vegetables', 18.00,   35.00,  0.00,  'pack',  10),
  ('Royal Gala Apples 1kg',     'Crisp imported gala apples',                 '8901725210861', 'FRV-APL-1K', 'Fruits & Vegetables',118.00,  169.00,  0.00,  'kg',    10),

  ('Mineral Water 1L',          'Packaged drinking water',                    '8904004218787', 'BEV-WTR-1L', 'Beverages',            9.00,   20.00, 12.00,  'bottle',24),
  ('Orange Juice 1L',           'No-added-sugar orange juice',                '8904004226706', 'BEV-JUS-1L', 'Beverages',           88.00,  125.00, 12.00,  'carton',10),
  ('Green Tea (25 Bags)',       'Pure green tea bags, box of 25',             '8904004234626', 'BEV-TEA-25', 'Beverages',          142.00,  199.00, 18.00,  'box',    6),
  ('Filter Coffee Powder 200g', 'Roast and ground filter coffee',             '8904004242546', 'BEV-COF-200','Beverages',          178.00,  245.00, 18.00,  'pack',   6),
  ('Cola 750ml',                'Chilled carbonated soft drink',              '5449000258380', 'BEV-COL-750','Beverages',           28.00,   45.00, 28.00,  'bottle',18),

  ('Potato Chips 52g',          'Classic salted potato crisps',               '5449000266293', 'SNK-CHP-52', 'Snacks',              14.00,   25.00, 12.00,  'pack',  20),
  ('Marie Biscuits 250g',       'Light tea biscuits',                         '5449000274212', 'SNK-BIS-250','Snacks',              26.00,   40.00, 18.00,  'pack',  15),
  ('Dark Chocolate 80g',        '55% cocoa dark chocolate bar',               '5449000282132', 'SNK-CHO-80', 'Snacks',              78.00,  110.00, 18.00,  'bar',   10),
  ('Roasted Almonds 200g',      'Lightly salted roasted almonds',             '5449000290052', 'SNK-ALM-200','Snacks',             218.00,  299.00, 12.00,  'pack',   6),
  ('Mixed Namkeen 200g',        'Traditional savoury mix',                    '8901063297975', 'SNK-NMK-200','Snacks',              42.00,   65.00, 12.00,  'pack',  12),

  ('Basmati Rice 5kg',          'Aged long-grain basmati',                    '8901063305892', 'STP-RIC-5K', 'Staples & Grains',   540.00,  695.00,  5.00,  'bag',    5),
  ('Atta Whole Wheat 5kg',      'Chakki-fresh whole wheat flour',             '8901063313811', 'STP-ATA-5K', 'Staples & Grains',   225.00,  289.00,  5.00,  'bag',    6),
  ('Toor Dal 1kg',              'Split pigeon peas',                          '8901063321731', 'STP-DAL-1K', 'Staples & Grains',   132.00,  178.00,  5.00,  'pack',   8),
  ('Sunflower Oil 1L',          'Refined sunflower cooking oil',              '8901063329652', 'STP-OIL-1L', 'Staples & Grains',   118.00,  155.00,  5.00,  'bottle',10),
  ('Iodised Salt 1kg',          'Free-flowing iodised table salt',            '8904004250466', 'STP-SLT-1K', 'Staples & Grains',    16.00,   28.00,  5.00,  'pack',  12)
) as s(name, description, barcode, sku, category, purchase_price, selling_price, tax_rate, unit, threshold)
join public.categories c on lower(c.name) = lower(s.category)
on conflict (barcode) do nothing;

-- -----------------------------------------------------------------------------
-- Opening stock
-- Routed through adjust_inventory() rather than a plain UPDATE so the seeded
-- quantities arrive with a matching ledger entry, exactly like real restocking.
-- The `i.quantity = 0` guard makes a second run a no-op.
-- -----------------------------------------------------------------------------
do $seed$
declare
  r record;
begin
  for r in
    select p.id as product_id, v.qty
    from (values
      ('8901030100000', 64), ('8901030107917', 40), ('8901030115837', 18),
      ('8901030123757', 26), ('8901030131677',  4),
      ('8901058139594', 32), ('8901058147513', 24), ('8901058155433', 15),
      ('8901058163353',  6), ('8901058171273', 21),
      ('8901725179199', 55), ('8901725187101', 48), ('8901725195021', 62),
      ('8901725202941',  7), ('8901725210861', 28),
      ('8904004218787',120), ('8904004226706', 22), ('8904004234626',  9),
      ('8904004242546', 14), ('5449000258380', 76),
      ('5449000266293', 90), ('5449000274212', 44), ('5449000282132', 31),
      ('5449000290052',  3), ('8901063297975', 38),
      ('8901063305892', 12), ('8901063313811', 19), ('8901063321731', 27),
      ('8901063329652', 33), ('8904004250466', 41)
    ) as v(barcode, qty)
    join public.products  p on p.barcode = v.barcode
    join public.inventory i on i.product_id = p.id
    where i.quantity = 0
  loop
    perform public.adjust_inventory(
      r.product_id, r.qty, 'purchase', 'Opening stock (seed)', null, 'seed', null
    );
  end loop;
end;
$seed$;

-- One product is left deliberately out of stock so the out-of-stock UI state is
-- visible without having to sell anything first. The write-off is derived from
-- the product's actual quantity rather than a hard-coded number, and guarded on
-- its own ledger entry so a second run is a no-op.
do $demo$
declare
  r record;
begin
  for r in
    select p.id as product_id, i.quantity
    from public.products p
    join public.inventory i on i.product_id = p.id
    where p.barcode = '8901063329652'
      and i.quantity > 0
      and not exists (
        select 1 from public.inventory_movements m
        where m.product_id = p.id and m.reason = 'Written off for demo'
      )
  loop
    perform public.adjust_inventory(
      r.product_id, -r.quantity, 'damage', 'Written off for demo', null, 'seed', null
    );
  end loop;
end;
$demo$;


-- ###########################################################################
-- ### Reload the PostgREST schema cache
-- ###########################################################################

notify pgrst, 'reload schema';
